[exp]
seed = 2024
n_seeds = 3

[methods]
considered = [
    "codi",
    "fairsmote",
    "fairtabddpm",
    "fairtabgan",
    "goggle",
    "great",
    "smote",
    "stasy",
    "tabddpm",
    "tabsyn",
]

[methods.codi]
session = "best"

[methods.fairsmote]
session = "best"

[methods.fairtabddpm]
session = "best"

[methods.fairtabgan]
session = "best"

[methods.goggle]
session = "best"

[methods.great]
session = "best"

[methods.smote]
session = "best"

[methods.stasy]
session = "best"

[methods.tabddpm]
session = "best"

[methods.tabsyn]
session = "best"

[classifiers]
mean = [
    "Random Forest",
    "SVM",
    "MLP",
    "XGBoost",
    "CatBoost",
    "Logistic Regression",
]
best = [
    "CatBoost",
]