[data]
name = "law"
path = "/rdf/db/public-tabular-datasets/"
batch_size = 8

[exp]
method = "great"
device = "cuda:1"
home = "/rdf/experiments/fair-tab-diffusion-exps/"
seed = 2024

[model]

[train]
n_epochs = 1

[sample]
n_seeds = 3

[eval]
sk_clf_choice = [
    "CatBoost",
]
