[data]
name = "law"
path = "/rdf/db/public-tabular-datasets/"
batch_size =  256

[exp]
method = "goggle"
device = "cuda:1"
home = "/rdf/experiments/fair-tab-diffusion-exps/"
seed = 2024

[model]
encoder_dim = 64
encoder_l = 2
decoder_dim = 64
decoder_l = 2

[train]
lr = 0.01
n_epochs = 1000

[sample]
n_seeds = 3

[eval]
sk_clf_choice = [
    "CatBoost",
]
