[data]
name = "compass"
path = "/rdf/db/public-tabular-datasets/"

[exp]
method = "fair-tab-gan"
device = "cuda:1"
home = "/rdf/experiments/fair-tab-diffusion-exps/"
seed = 2024

[train]
batch_size = 256
n_epochs = 200
fair_epochs = 20
lr = 0.0002

[sample]
n_seeds = 3

[eval]
sk_clf_choice = [
    "CatBoost",
]
