[exp]
name = 'tune'
mode = 'unet'
device = 'cuda'
home = './exdir/unimodal/adult/'
pretrained = false
seed = 2023
n_seeds = 5

[guid]
warmup_steps = 0
cond_guid_weight = 1.0
cond_guid_threshold = 1.0
cond_momentum_weight = 0.5
cond_momentum_beta = 0.5
overall_guid_weight = 1.0

[data]
path = './db-seq/unimodal/adult/'
batch_size = 1024

[model]
parametrization = 'eps'
scheduler = 'cosine'
max_beta = 0.2
n_timesteps = 100
d_x_emb = 64
d_t_emb = 128
d_cond_emb = 120
n_base_channels = 16
n_groups = 8
n_channels_factors = [2, 2]
n_res_blocks = 1
n_tf_layers = 1
n_heads = 1
attention_levels = [0]

[mlp]
d_layers = [128, 1024, 1024, 1024, 1024, 1024]
dropout = 0.0

[train]
n_epochs = 4000
lr = 1e-3
weight_decay = 0.0
max_non_improve = 500

[sample]
dist = 'fair'
n_samples = 5000
batch_size = 1000

[eval]
sk_clf_choice = ['decision-tree', 'random-forest', 'mlp', 'xgboost', 'svm']

[plot]
cat_cols = ['sex', 'race']
num_cols = ['hours-per-week']
