[data]
name = "adult"
path = "/rdf/db/public-tabular-datasets/"

[exp]
method = "stasy"
home = "/rdf/experiments/fair-tab-diffusion-exps/"
seed = 2024

[model]

[train]

[sample]
n_seeds = 3

[eval]
sk_clf_choice = [
    "CatBoost",
]
