[data]
name = "adult"
path = "/rdf/db/public-tabular-datasets/"

[exp]
method = "fairsmote"
home = "/rdf/experiments/fair-tab-diffusion-exps/"
seed = 2024

[model]
knn = 5

[sample]
n_seeds = 3

[eval]
sk_clf_choice = [
    "CatBoost",
]
