[data]
name = "german"
path = "/rdf/db/public-tabular-datasets/"
batch_size =  256

[exp]
method = "goggle"
device = "cuda:1"
home = "/rdf/experiments/fair-tab-diffusion-exps/"
seed = 2024

[model]
encoder_dim = 512
encoder_l = 4
decoder_dim = 512
decoder_l = 4

[train]
lr = 0.001
n_epochs = 4000

[sample]
n_seeds = 3

[eval]
sk_clf_choice = [
    "CatBoost",
]
